server:
  port: 3333

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: products-api
              uri: lb://products-api
              predicates:
                - Path=/api/products/**

            - id: user-api
              uri: lb://user-api
              predicates:
                - Path=/api/user/**

            - id: order-api
              uri: lb://order-api
              predicates:
                - Path=/api/order/**

            - id: notifications-api
              uri: lb://notifications-api
              predicates:
                - Path=/api/notifications/**

            - id: admin-api
              uri: lb://admin-api
              predicates:
                - Path=/api/admin/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.cloud.loadbalancer: DEBUG
