server:
  port: 7073

spring:
  application:
    name: products-api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  boot:
    admin:
      client:
        url: http://localhost:1111/

management:
  endpoints:
    web:
      exposure:
        include: "*"


