server:
  port: 7073

spring:
  application:
    name: products-api

  datasource:
    url: jdbc:mysql://localhost:3306/ecomm_dev_db
    username: root
    password: Rushikesh
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
     
